/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lq_testopencv_OpenCVHelper */

#ifndef _Included_com_example_lq_testopencv_OpenCVHelper
#define _Included_com_example_lq_testopencv_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lq_testopencv_OpenCVHelper
 * Method:    grayImage
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_example_lq_testopencv_OpenCVHelper_nativeProcessImage
  (JNIEnv *, jclass, jobject, jobject, jint);

JNIEXPORT jint JNICALL Java_com_example_lq_testopencv_OpenCVHelper_nativeFindContours
        (JNIEnv *, jclass, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
